spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: https://www.google.com
          predicates:
            - Path=/google

server:
  port: 8090