spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: https://www.google.com
          predicates:
            - Path=/google

management:
  endpoints:
    web:
      exposure:
        include: beans, loggers, health, info

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    root: DEBUG